version: '3.5'
services:
  pipeline:
    build:
      context: ./qanary_pipeline-template
      args:
        JAR_FILE: ${PIPELINE_NAME}-${PIPELINE_VERSION}.jar
    image: ${PIPELINE_IMAGE}:${PIPELINE_VERSION}
    ports:
      - "${PIPELINE_PORT}:8080"
    networks:
      pipeline:
        ipv4_address: 172.25.0.2

  config-ui:
    build:
      context: ./qanary-configuration-frontend
      args:
        REACT_APP_HOST: ${PIPELINE_HOST}
        REACT_APP_PORT: ${PIPELINE_PORT}
    image: ${UI_IMAGE}:${UI_VERSION}
    ports:
      - "${UI_PORT}:80"
    networks:
      pipeline:
        ipv4_address: 172.25.0.3

networks:
  pipeline:
    driver: bridge
    name: pipeline-net
    ipam:
      config:
        - subnet: 172.25.0.0/24